version: '3.7'

services:
  licensingservice:

    image: licensing-service:latest

    ports:
      - "8080:8080"

    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

    networks:
      backend:
        aliases:
          - "licenseservice"

networks:
  backend:
    driver: bridge